### ISSUE TITLE
DACT Fails after first installation

### ISSUE THREAD

**Issue by bornhaeusser** [Sleepcap/vDiplomacy#11]
DACT Fails

> Error triggered: Missing argument 13 for processGame::create(), called in /volume1/web/game/vDiplomacy/datc/datcGame.php on line 60 and defined
> 
> Error: "Missing argument 13 for processGame::create(), called in /volume1/web/game/vDiplomacy/datc/datcGame.php on line 60 and defined"
> Raised: "/volume1/web/game/vDiplomacy/gamemaster/game.php"
> Line: "297"
> userID = 5Variable dump: variantID => 1
> name => DATC-Adjudicator-Test
> password => 
> bet => 5
> potType => Winner-takes-all
> phaseMinutes => 30
> joinPeriod => 30
> anon => No
> press => Regular
> missingPlayerPolicy => Normal
> drawType => draw-votes-hidden
> rrLimit => 0
> 
> 
> Trace:
> 0 => Array: (
> file => /volume1/web/game/vDiplomacy/gamemaster/game.php
> line => 297
> function => error_handler
> args => Array: (
> 0 => 2
> 1 => Missing argument 13 for processGame::create(), called in /volume1/web/game/vDiplomacy/datc/datcGame.php on line 60 and defined
> 2 => /volume1/web/game/vDiplomacy/gamemaster/game.php
> 3 => 297
> 4 => Array: (
> variantID => 1
> name => DATC-Adjudicator-Test
> password => 
> bet => 5
> potType => Winner-takes-all
> phaseMinutes => 30
> joinPeriod => 30
> anon => No
> press => Regular
> missingPlayerPolicy => Normal
> drawType => draw-votes-hidden
> rrLimit => 0
> )
> )
> )
> 1 => Array: (
> file => /volume1/web/game/vDiplomacy/datc/datcGame.php
> line => 60
> function => create
> class => processGame
> type => ::
> args => Array: (
> 0 => 1
> 1 => DATC-Adjudicator-Test
> 2 => 
> 3 => 5
> 4 => Winner-takes-all
> 5 => 30
> 6 => 30
> 7 => No
> 8 => Regular
> 9 => Normal
> 10 => draw-votes-hidden
> 11 => 0
> )
> )
> 2 => Array: (
> file => /volume1/web/game/vDiplomacy/datc/interactive.php
> line => 160
> function => __construct
> class => datcGame
> object => Array: (
> id => 
> variantID => 
> Variant => 
> password => 
> turn => 
> phase => 
> attempts => 
> processTime => 
> private => 
> name => 
> gameOver => 
> pot => 
> phaseMinutes => 
> Members => 
> Scoring => 
> potType => 
> drawType => 
> processStatus => 
> pauseTimeRemaining => 
> minimumBet => 
> anon => 
> pressType => 
> lockMode => 
> missingPlayerPolicy => 
> minimumReliabilityRating => 
> civilDisorderInfo => 
> maxTurns => 
> targetSCs => 
> minPhases => 
> specialCDcount => 
> specialCDturns => 
> rlPolicy => 
> chessTime => 
> adminLock => 
> directorUserID => 
> chooseYourCountry => 
> description => 
> noProcess => 
> blockVotes => 
> fixStart => 
> potModifier => 
> )
> type => ->
> args => Array: (
> 0 => 101
> )
> )
> 3 => Array: (
> file => /volume1/web/game/vDiplomacy/datc.php
> line => 33
> args => Array: (
> 0 => /volume1/web/game/vDiplomacy/datc/interactive.php
> )
> function => require_once
> )
> .
> 
> This was probably caused by a software bug. If these occur often try enabling error-logging via config.php, and report errors to the official devs for help.

**Comment by bornhaeusser** [comment]
in dactgame.php line 60 is there missing some entries?

`			$Game = processGame::create(1, 'DATC-Adjudicator-Test', '', 5,'Winner-takes-all', 30,30,'No','Regular', 'Normal', 'draw-votes-hidden', 0);`

**Comment by Sleepcap** [comment]
I added all necessary parameters to the call, but the Adjucator-tests still fail.
As I never used this and have absolutely no clue about this, I can't fix this here.
Maybe someone else can figure out what's going wrong here.

**Comment by Sleepcap** [comment]
This is fixed now.
First the gamecreate has more options, than the interactive-map did screw the order-generation of the test-cases and last our new "improved" javascript does not allow for many of the "wrong" orders to be submitted to the server.
It does now load the "old" javascript-code for the datC tests, and the gamecreate-calls are now correct too.

**Comment by Sleepcap** [comment]
Tobi found some problems with the new javascript-convoy-code and fixed everything.
The DATC tests work now with our new and improved JS-code too.
