### ISSUE TITLE
Wasaka or Wakasa?

### ISSUE THREAD

**Issue by jwoelmer2** [Sleepcap/vDiplomacy#16]
Bug report for the Sengoku vdip map. [](http://vdiplomacy.com/variants.php?variantID=27)
The territory on the map itself is shown as Wasaka Bay, but when I tried moving my fleet there from Noto, it came up as "Wakasa Bay." Obviously not a huge deal, but it's something you might want to patch.

**Comment by Sleepcap** [comment]
Thanks. Inwill take care of this.

**Comment by Sleepcap** [comment]
Thanks. It's Wakasa. There was a spelling error on the smallmap.
It's fixed now.
