### ISSUE TITLE
RSS ID Generating Problem

### ISSUE THREAD

**Issue by bornhaeusser** [Sleepcap/vDiplomacy#18]
If i generate a new RSS ID a new Site appears with no content - just the header. And no RSS was generated.

**Comment by Sleepcap** [comment]
Can you please be more specific?
I tried on the live and on my dev-server and the RSS-ID works just fine.

**Comment by bornhaeusser** [comment]
Ok let me try. After a new installation the rss id is emty. if i click on generate a new site appears but nothing happens.

![image](https://user-images.githubusercontent.com/6609040/39032655-bb9c948a-446e-11e8-85ee-cebb7e5e96b1.png)


Also if i write one in the database manually - then i see the rss link. after deleting the rss link and click on generate a new one again blank page like in the screenshoot.

**Comment by Sleepcap** [comment]
Sorry, can't reproduce this. Works without any problems every install I tried.

**Comment by bornhaeusser** [comment]
ok, thanks. i will check
